# Generated by Django 3.2 on 2024-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrolearn_modules_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrolearnmoduleslist',
            name='organization',
        ),
        migrations.AddField(
            model_name='hydrolearnmoduleslist',
            name='tag_filter',
            field=models.CharField(default='nwm_portal_module', max_length=200),
        ),
    ]
