# Generated by Django 3.2 on 2023-10-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroShareResource',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='backend_hydroshareresource', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='resource title', max_length=50)),
                ('subtitle', models.CharField(default='resource subtitle', max_length=50)),
                ('image', models.CharField(default='https://placehold.co/400', max_length=50)),
                ('description', models.CharField(default='resource description', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
