# Generated by Django 3.2 on 2023-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroshareresource',
            name='documentation_url',
            field=models.CharField(default='https://about.readthedocs.com/?ref=readthedocs.com', max_length=50),
        ),
        migrations.AddField(
            model_name='hydroshareresource',
            name='github_url',
            field=models.CharField(default='https://github.com/', max_length=50),
        ),
        migrations.AddField(
            model_name='hydroshareresource',
            name='web_site_url',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='hydroshareresource',
            name='description',
            field=models.TextField(default='resource description', max_length=150),
        ),
    ]
