# Generated by Django 3.2 on 2023-10-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20231004_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroshareresource',
            name='documentation_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hydroshareresource',
            name='github_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hydroshareresource',
            name='web_site_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
