# Generated by Django 3.2 on 2023-10-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_hydroshareresource_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroshareresource',
            name='description',
            field=models.TextField(default='resource description'),
        ),
    ]
