# Generated by Django 3.2 on 2023-11-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20231017_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroshareresource',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='hydroshareresource',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
