# Generated by Django 3.2 on 2023-11-02 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('backend', '0011_auto_20231101_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroBibliographyResource',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='backend_zoterobibliographyresource', serialize=False, to='cms.cmsplugin')),
                ('api_key', models.CharField(default='api_key', max_length=200)),
                ('library_type', models.CharField(default='user', max_length=200)),
                ('library_id', models.CharField(default='library_id', max_length=200)),
                ('collection_id', models.CharField(default='library_id', max_length=200)),
                ('style', models.CharField(default='apa', max_length=200)),
                ('html', models.JSONField(editable=False)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
