# Generated by Django 3.2 on 2023-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_zoterobibliographyresource_name_of_page_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterobibliographyresource',
            name='link_of_library_or_collection',
            field=models.CharField(default='', max_length=400),
        ),
    ]
