# Generated by Django 3.2 on 2023-11-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_zoterobibliographyresource_link_of_library_or_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterobibliographyresource',
            name='name_of_page_created',
        ),
    ]
