# Generated by Django 3.2 on 2023-12-04 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('backend', '0024_remove_zoterobibliographyresource_name_of_page_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroShareResourceList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='backend_hydroshareresourcelist', serialize=False, to='cms.cmsplugin')),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('width', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(400)])),
                ('height', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(400)])),
                ('tags', models.CharField(default='', max_length=200)),
                ('updated_version', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
