# Generated by Django 3.2 on 2023-12-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_hydroshareresourcelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydroshareresourcelist',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hydroshareresourcelist',
            name='width',
        ),
        migrations.AddField(
            model_name='hydroshareresourcelist',
            name='resources',
            field=models.JSONField(default={}, editable=False),
        ),
    ]
