# Generated by Django 3.2 on 2024-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_hydrolearnmoduleslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterobibliographyresource',
            name='is_saving',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
