# Generated by Django 3.2 on 2024-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('backend', '0030_zoterobibliographyresource_is_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterobibliographyresource',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='HydroLearnModulesList',
        ),
        migrations.DeleteModel(
            name='ZoteroBibliographyResource',
        ),
    ]
