# Generated by Django 3.2 on 2024-03-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('backend', '0031_auto_20240325_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydroShareResource',
        ),
    ]
