# Generated by Django 3.2 on 2024-03-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('backend', '0032_delete_hydroshareresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydroShareResourceList',
        ),
    ]
