# Generated by Django 3.2 on 2024-03-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroPublications',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='publications_zoteropublications', serialize=False, to='cms.cmsplugin')),
                ('api_key', models.CharField(default='', max_length=200)),
                ('library_type', models.CharField(default='', max_length=200)),
                ('library_id', models.CharField(default='', max_length=200)),
                ('collection_id', models.CharField(blank=True, default='', max_length=200)),
                ('style', models.CharField(default='apa', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='ZoteroBibliographyResource',
        ),
    ]
