# Generated by Django 3.2 on 2024-03-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_publications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoteropublications',
            name='publications',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
