# Generated by Django 3.2 on 2024-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_publications_app', '0002_zoteropublications_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoteropublications',
            name='local_remote_version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
